//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/Controles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controles : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controles"",
    ""maps"": [
        {
            ""name"": ""Jogo"",
            ""id"": ""ddcbaf91-0e52-4991-86e6-21ee895b78e2"",
            ""actions"": [
                {
                    ""name"": ""NorteSul"",
                    ""type"": ""Button"",
                    ""id"": ""843c9d49-0a82-4471-995e-9ed11441b302"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LesteOeste"",
                    ""type"": ""Button"",
                    ""id"": ""7ef9bf15-ee54-483d-8c25-dcf09b665760"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ataque"",
                    ""type"": ""Button"",
                    ""id"": ""73655146-782b-438e-aa51-cb0e321b19e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Setas"",
                    ""id"": ""f54e2477-d500-40a6-9bfe-18fc1d8f7b79"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NorteSul"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""06152b7a-c945-46f5-8169-3b8c6df7bd6c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NorteSul"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9aaa3dd4-bbd9-42f5-8898-4b161e7a5d74"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NorteSul"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ASDW"",
                    ""id"": ""581df0ff-e3fd-45d1-8db1-443ec4db4f9c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NorteSul"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9f90af9a-c33f-4066-a38d-55c9e11370e1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NorteSul"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""478dee9e-22cb-4c2e-99d1-0a0ac50efda0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NorteSul"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Setas"",
                    ""id"": ""c39d18bf-e55a-4b56-93e8-6f8ef2fec276"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LesteOeste"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bc2954d7-c1ef-4cb4-a5a8-df1dc18d1c89"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LesteOeste"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""acb31d84-412d-4eb8-8398-50480f74f187"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LesteOeste"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ASDW"",
                    ""id"": ""e649e222-1be7-4511-ac3b-5c4328de2928"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LesteOeste"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b3921f7f-bdbf-4021-b617-879857d59417"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LesteOeste"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""190fa08c-a247-467d-b170-289f6271231b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LesteOeste"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7869526e-020b-4040-bff2-8b26c9a611b7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ataque"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Jogo
        m_Jogo = asset.FindActionMap("Jogo", throwIfNotFound: true);
        m_Jogo_NorteSul = m_Jogo.FindAction("NorteSul", throwIfNotFound: true);
        m_Jogo_LesteOeste = m_Jogo.FindAction("LesteOeste", throwIfNotFound: true);
        m_Jogo_Ataque = m_Jogo.FindAction("Ataque", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Jogo
    private readonly InputActionMap m_Jogo;
    private IJogoActions m_JogoActionsCallbackInterface;
    private readonly InputAction m_Jogo_NorteSul;
    private readonly InputAction m_Jogo_LesteOeste;
    private readonly InputAction m_Jogo_Ataque;
    public struct JogoActions
    {
        private @Controles m_Wrapper;
        public JogoActions(@Controles wrapper) { m_Wrapper = wrapper; }
        public InputAction @NorteSul => m_Wrapper.m_Jogo_NorteSul;
        public InputAction @LesteOeste => m_Wrapper.m_Jogo_LesteOeste;
        public InputAction @Ataque => m_Wrapper.m_Jogo_Ataque;
        public InputActionMap Get() { return m_Wrapper.m_Jogo; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JogoActions set) { return set.Get(); }
        public void SetCallbacks(IJogoActions instance)
        {
            if (m_Wrapper.m_JogoActionsCallbackInterface != null)
            {
                @NorteSul.started -= m_Wrapper.m_JogoActionsCallbackInterface.OnNorteSul;
                @NorteSul.performed -= m_Wrapper.m_JogoActionsCallbackInterface.OnNorteSul;
                @NorteSul.canceled -= m_Wrapper.m_JogoActionsCallbackInterface.OnNorteSul;
                @LesteOeste.started -= m_Wrapper.m_JogoActionsCallbackInterface.OnLesteOeste;
                @LesteOeste.performed -= m_Wrapper.m_JogoActionsCallbackInterface.OnLesteOeste;
                @LesteOeste.canceled -= m_Wrapper.m_JogoActionsCallbackInterface.OnLesteOeste;
                @Ataque.started -= m_Wrapper.m_JogoActionsCallbackInterface.OnAtaque;
                @Ataque.performed -= m_Wrapper.m_JogoActionsCallbackInterface.OnAtaque;
                @Ataque.canceled -= m_Wrapper.m_JogoActionsCallbackInterface.OnAtaque;
            }
            m_Wrapper.m_JogoActionsCallbackInterface = instance;
            if (instance != null)
            {
                @NorteSul.started += instance.OnNorteSul;
                @NorteSul.performed += instance.OnNorteSul;
                @NorteSul.canceled += instance.OnNorteSul;
                @LesteOeste.started += instance.OnLesteOeste;
                @LesteOeste.performed += instance.OnLesteOeste;
                @LesteOeste.canceled += instance.OnLesteOeste;
                @Ataque.started += instance.OnAtaque;
                @Ataque.performed += instance.OnAtaque;
                @Ataque.canceled += instance.OnAtaque;
            }
        }
    }
    public JogoActions @Jogo => new JogoActions(this);
    public interface IJogoActions
    {
        void OnNorteSul(InputAction.CallbackContext context);
        void OnLesteOeste(InputAction.CallbackContext context);
        void OnAtaque(InputAction.CallbackContext context);
    }
}
